apiVersion: v1
kind: Pod
metadata:
  name: myfirstgoapp
  labels:
    app: myfirstgoapp
spec:
  containers:
    - name: myfirstgoapp
      image: {{.Values.image}}
      ports:
      - containerPort: 12345
